import mongoose from "mongoose";

const TradeSchema = new mongoose.Schema(
  {
    user_id: { type: String, required: true },
    symbol: String,
    updated_at: String,
    date: String,
    last_event: {
      event: String,
      ts: String,
      payload: {
        action: String,
        active_trades: {
          positions: Array,
          total_profit_usd: Number,
          count: Number,
          ok: Boolean,
        },
        block_reason: String,
        current_bid: Number,
        daily_done: Boolean,
        decision: String,
        did_trade: Boolean,
        mode: String,
        pips_moved: Number,
        profit_usd: Number,
        realized_profit_usd: Number,
        risk: {
          floating_now: Number,
          floating_usd: Number,
          force_close: Boolean,
          halt: Boolean,
          loss_lock: Number,
          open_count: Number,
          profit_lock: Number,
          realized_today: Number,
          realized_usd: Number,
          reason: String,
          total_pnl: Number,
          total_usd: Number,
        },
        risk_from_threshold: {
          floating_usd: Number,
          force_close: Boolean,
          halt: Boolean,
          open_count: Number,
          realized_usd: Number,
          reason: String,
          total_usd: Number,
        },
        start_price: Number,
        symbol: String,
        telemetry: {
          bias: String,
          crossed_1x: Boolean,
          crossed_1x_bias: String,
          crossed_1x_now: Boolean,
          crossed_1x_time: String,
          entry_mode: String,
          in_entry_window: Boolean,
          jumped_over_long: Boolean,
          jumped_over_short: Boolean,
          late_armed: Boolean,
          miss_reason: String,
          momentum_tp_price: Number,
          open_count: Number,
          probe_dn: Number,
          probe_up: Number,
          risk_force_close: Boolean,
          risk_halt: Boolean,
          risk_reason: String,
          window_hit_count_long: Number,
          window_hit_count_short: Number,
          x_now: Number,
        },
        threshold_x: Number,
        zone_id: Number,
      },
    },
  },
  { collection: "Astra-symbol-trades", timestamps: false, strict: false },
);

export default mongoose.models.Trade || mongoose.model("Trade", TradeSchema);
