import type { CSSProperties } from 'vue'
import type { Theme } from '@/themes'

// ---------------------------------------------------------------------------
// pxify: the design's style objects use raw numbers for pixel values (React
// convention). Vue's :style does NOT auto-append "px", so we do it here,
// skipping the well-known unitless properties.
// ---------------------------------------------------------------------------
const UNITLESS = new Set([
  'animationIterationCount',
  'columnCount',
  'columns',
  'flex',
  'flexGrow',
  'flexShrink',
  'fontWeight',
  'gridArea',
  'gridRow',
  'gridColumn',
  'lineClamp',
  'lineHeight',
  'opacity',
  'order',
  'orphans',
  'tabSize',
  'widows',
  'zIndex',
  'zoom',
  'fillOpacity',
  'floodOpacity',
  'stopOpacity',
  'strokeOpacity',
  'strokeWidth',
])

export type Style = Record<string, string | number | undefined>

export function pxify(style: Style): CSSProperties {
  const out: Record<string, string | number> = {}
  for (const key in style) {
    const val = style[key]
    if (val === undefined) continue
    if (typeof val === 'number' && !UNITLESS.has(key)) out[key] = val + 'px'
    else out[key] = val
  }
  return out as CSSProperties
}

// Merge two raw styles then pxify (later wins).
export function merge(...styles: (Style | undefined)[]): CSSProperties {
  const combined: Style = {}
  for (const s of styles) if (s) Object.assign(combined, s)
  return pxify(combined)
}

// A gentle floating "bob" animation, parameterised like the design's bob().
export function bob(delay: number, dur: number): Style {
  return { animation: 'bob ' + dur + 's ease-in-out infinite', animationDelay: delay + 's' }
}

// ---------------------------------------------------------------------------
// buildStyles: the full `s` style map, ported from the design's renderVals().
// Only theme + viewport dependent styles live here; a handful of styles that
// also depend on component-local state (drawer open, dialog closing, dragging,
// the signed-in user's colour) are built inside the components that own them.
// ---------------------------------------------------------------------------
export function buildStyles(c: Theme, dark: boolean, isMobile: boolean) {
  const B = '1px solid ' + c.border

  const tickerBase: Style = {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: c.glass,
    backdropFilter: 'blur(24px) saturate(1.5)',
    border: B,
    color: c.text,
    cursor: 'pointer',
    transition: 'transform .25s ease',
  }
  const ticker: Style = isMobile
    ? {
        ...tickerBase,
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 8,
        borderRadius: 0,
        justifyContent: 'center',
        padding: '8px 12px',
      }
    : {
        ...tickerBase,
        position: 'fixed',
        top: 20,
        right: 20,
        zIndex: 8,
        borderRadius: 14,
        padding: '9px 14px',
        maxWidth: 'min(60vw,260px)',
        boxShadow: c.shadow,
        ...bob(2.4, 6.5),
      }

  const s: Record<string, Style> = {
    page: {
      position: 'relative',
      zIndex: 1,
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: isMobile ? '56px 12px 100px' : '40px 16px',
    },
    stack: {
      position: 'relative',
      isolation: 'isolate',
      width: isMobile ? '96vw' : 'min(92vw, 720px)',
      display: 'flex',
      flexDirection: 'column',
      gap: 22,
    },
    topRow: {
      position: 'relative',
      zIndex: 12,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: '0 4px',
    },
    brand: {
      fontSize: 15,
      letterSpacing: '0.42em',
      fontWeight: 600,
      color: c.text,
      textShadow: dark ? '0 0 16px rgba(255,255,255,0.15)' : 'none',
    },
    themeWrap: { position: 'relative' },
    themeTrigger: {
      width: 36,
      height: 36,
      borderRadius: '50%',
      background: c.pageBg,
      border: '2px solid ' + c.accent,
      boxShadow: '0 0 14px ' + c.accent,
      cursor: 'pointer',
      ...bob(1.6, 7),
    },
    themePanel: {
      position: 'absolute',
      top: 'calc(100% + 12px)',
      right: 0,
      zIndex: 20,
      width: 220,
      background: c.glass,
      backdropFilter: 'blur(28px) saturate(1.6)',
      border: B,
      borderRadius: 24,
      padding: 10,
      boxShadow: c.shadow,
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      animation: 'fadeUp .25s ease both',
    },
    themeGroupLabel: {
      fontSize: 10,
      letterSpacing: '0.12em',
      textTransform: 'uppercase',
      color: c.dim,
      padding: '6px 8px 2px',
    },
    themeRowHover: { background: c.card },
    greetingRow: {
      position: 'relative',
      zIndex: 12,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      padding: isMobile ? '11px 11px 11px 18px' : '13px 13px 13px 20px',
      borderRadius: 26,
      background: c.glass,
      backdropFilter: 'blur(20px) saturate(1.5)',
      '-webkit-backdrop-filter': 'blur(20px) saturate(1.5)',
      border: B,
      boxShadow: c.shadow + ', inset 0 1px 0 rgba(255,255,255,0.14)',
      ...bob(1.2, 6.4),
    },
    greetingText: { fontSize: 14, color: c.text },
    greetingLeft: { display: 'flex', alignItems: 'center', gap: 10 },
    userMenuWrap: { position: 'relative', zIndex: 13, flexShrink: 0 },
    userPill: {
      display: 'flex',
      alignItems: 'center',
      gap: 9,
      padding: '5px 11px 5px 5px',
      borderRadius: 999,
      background: c.input,
      border: B,
      cursor: 'pointer',
      boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.12)',
      transition: 'background .25s ease, transform .2s ease',
    },
    userPillHover: { transform: 'translateY(-1px)', background: c.card },
    userPillName: { fontSize: 12, fontWeight: 600, color: c.text, whiteSpace: 'nowrap' },
    userPillChevron: { fontSize: 9, color: c.dim, marginLeft: -3 },
    dayGroups: {
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      maxHeight: isMobile ? 300 : 400,
      overflowY: 'auto',
      margin: '0 -2px',
      padding: 2,
    },
    dayGroupHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
    dayGroupLabelBase: {
      fontSize: 10,
      fontWeight: 700,
      letterSpacing: '0.14em',
      textTransform: 'uppercase',
      color: c.accent,
    },
    dayCount: { fontSize: 10, color: c.dim, fontWeight: 600 },
    dayDropHint: {
      fontSize: 11,
      color: c.dim,
      textAlign: 'center',
      padding: '12px 0',
      fontStyle: 'italic',
    },
    grip: {
      display: 'grid',
      gridTemplateColumns: 'repeat(2,3px)',
      gridAutoRows: '3px',
      gap: 3,
      flexShrink: 0,
      cursor: 'grab',
      opacity: 0.45,
      alignContent: 'center',
    },
    gripDot: { width: 3, height: 3, borderRadius: '50%', background: c.dim },
    ghConnRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    prLink: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      color: c.accent,
      textDecoration: 'none',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    taskViewOverlay: {
      position: 'fixed',
      inset: 0,
      zIndex: 18,
      background: 'rgba(5,5,15,0.45)',
      backdropFilter: 'blur(6px)',
    },
    taskViewPage: {
      position: 'fixed',
      inset: 0,
      zIndex: 19,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      padding: isMobile ? '70px 16px' : '80px 24px',
    },
    taskViewBack: {
      position: 'fixed',
      top: 18,
      left: 18,
      zIndex: 20,
      display: 'flex',
      alignItems: 'center',
      gap: 6,
      fontSize: 13,
      fontWeight: 600,
      padding: '9px 16px',
      borderRadius: 14,
      border: B,
      background: c.glass,
      backdropFilter: 'blur(20px) saturate(1.5)',
      color: c.text,
      cursor: 'pointer',
      boxShadow: c.shadow,
    },
    taskViewCard: {
      width: 'min(94vw,560px)',
      maxHeight: '80vh',
      overflowY: 'auto',
      background: c.glass,
      backdropFilter: 'blur(34px) saturate(1.7)',
      border: B,
      borderRadius: 34,
      padding: isMobile ? '28px 22px' : '40px 38px',
      boxShadow: c.shadow,
      color: c.text,
      display: 'flex',
      flexDirection: 'column',
      gap: 18,
      animation: 'springIn .45s cubic-bezier(.34,1.56,.64,1) both',
    },
    taskViewTitle: {
      fontSize: isMobile ? 26 : 34,
      fontWeight: 700,
      lineHeight: 1.15,
      letterSpacing: '-0.01em',
      color: c.text,
      textWrap: 'pretty',
    },
    taskViewMeta: { display: 'flex', flexWrap: 'wrap', gap: 10 },
    taskViewMetaItem: {
      display: 'flex',
      flexDirection: 'column',
      gap: 3,
      padding: '10px 14px',
      borderRadius: 16,
      background: c.input,
      border: B,
      minWidth: 110,
    },
    taskViewMetaLabel: {
      fontSize: 9,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      color: c.dim,
    },
    taskViewMetaVal: { fontSize: 13, color: c.text },
    taskViewNotes: {
      fontSize: 14,
      lineHeight: 1.6,
      color: c.text,
      padding: '16px 18px',
      borderRadius: 16,
      background: c.input,
      border: B,
      whiteSpace: 'pre-wrap',
    },
    tabBar: isMobile
      ? {
          position: 'fixed',
          left: 14,
          right: 14,
          bottom: 14,
          zIndex: 8,
          background: c.glass,
          backdropFilter: 'blur(24px) saturate(1.5)',
          '-webkit-backdrop-filter': 'blur(24px) saturate(1.5)',
          borderRadius: 26,
          padding: 6,
          border: '1.5px solid ' + c.border,
          boxShadow: c.shadow + ', inset 0 1px 0 rgba(255,255,255,0.14)',
          overflow: 'hidden',
        }
      : {
          position: 'relative',
          zIndex: 4,
          alignSelf: 'center',
          maxWidth: '100%',
          background: c.glass,
          backdropFilter: 'blur(24px) saturate(1.5)',
          '-webkit-backdrop-filter': 'blur(24px) saturate(1.5)',
          borderRadius: 26,
          padding: 6,
          border: '1.5px solid ' + c.border,
          boxShadow: c.shadow + ', inset 0 1px 0 rgba(255,255,255,0.14)',
          overflow: 'hidden',
          ...bob(0, 6),
        },
    tabScroll: {
      position: 'relative',
      display: 'flex',
      gap: isMobile ? 4 : 6,
      width: isMobile ? '100%' : 'auto',
      overflowX: 'auto',
      overflowY: 'hidden',
      scrollSnapType: 'x mandatory',
      scrollbarWidth: 'none',
      '-webkit-overflow-scrolling': 'touch',
      maskImage: 'linear-gradient(90deg,transparent 0,#000 16px,#000 calc(100% - 16px),transparent 100%)',
      '-webkit-mask-image':
        'linear-gradient(90deg,transparent 0,#000 16px,#000 calc(100% - 16px),transparent 100%)',
    },
    indicator: {
      position: 'absolute',
      zIndex: 1,
      top: 0,
      bottom: 0,
      left: 0,
      width: 0,
      opacity: 0,
      background: c.card,
      backdropFilter: 'blur(10px) saturate(1.5)',
      '-webkit-backdrop-filter': 'blur(10px) saturate(1.5)',
      borderRadius: 18,
      border: '1px solid ' + c.border,
      boxShadow:
        'inset 0 1px 0 rgba(255,255,255,0.38), inset 0 -2px 3px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.08)',
      pointerEvents: 'none',
      transition:
        'transform .45s cubic-bezier(.5,1.4,.35,1), width .45s cubic-bezier(.5,1.4,.35,1), opacity .3s ease',
    },
    container: {
      position: 'relative',
      zIndex: 1,
      width: '100%',
      maxWidth: isMobile ? '100%' : 720,
      minHeight: isMobile ? 280 : 440,
      background: c.glass,
      backdropFilter: 'blur(30px) saturate(1.6)',
      '-webkit-backdrop-filter': 'blur(30px) saturate(1.6)',
      border: B,
      borderRadius: 34,
      padding: isMobile ? '22px' : 'clamp(24px,3.2vw,36px)',
      boxShadow: c.shadow,
      color: c.text,
      transition: 'background .8s ease, color .8s ease, border-color .8s ease, box-shadow .8s ease',
      ...bob(0.8, 6.6),
    },
    inputRow: { display: 'flex', gap: 9 },
    input: {
      flex: 1,
      minWidth: 0,
      padding: '13px 16px',
      borderRadius: 16,
      border: B,
      background: c.input,
      color: c.text,
      fontSize: 14,
      transition: 'background .4s ease, border-color .4s ease',
    },
    amountInput: {
      width: 120,
      flexShrink: 0,
      padding: '13px 16px',
      borderRadius: 16,
      border: B,
      background: c.input,
      color: c.text,
      fontSize: 14,
      transition: 'background .4s ease, border-color .4s ease',
    },
    select: {
      flex: 1,
      minWidth: 0,
      padding: '13px 14px',
      borderRadius: 16,
      border: B,
      background: c.input,
      color: c.text,
      fontSize: 14,
      cursor: 'pointer',
      transition: 'background .4s ease, border-color .4s ease',
    },
    addBtn: {
      flexShrink: 0,
      width: 48,
      borderRadius: 16,
      border: B,
      background: c.card,
      color: c.accent,
      fontSize: 21,
      cursor: 'pointer',
      boxShadow: dark ? '0 0 16px ' + c.accent : 'none',
      transition: 'transform .25s ease, box-shadow .25s ease',
    },
    addBtn2: {
      alignSelf: 'flex-start',
      fontSize: 12,
      padding: '8px 14px',
      borderRadius: 14,
      border: B,
      background: c.card,
      color: c.accent,
      cursor: 'pointer',
      fontWeight: 600,
    },
    addBtnHover: { transform: 'translateY(-2px)', boxShadow: '0 8px 18px rgba(0,0,0,0.25)' },
    empty: { textAlign: 'center', color: c.dim, fontSize: 13, padding: '18px 0' },
    list: {
      display: 'flex',
      flexDirection: 'column',
      gap: 9,
      maxHeight: isMobile ? 280 : 360,
      overflowY: 'auto',
      margin: '0 -2px',
      padding: '2px 2px',
    },
    rowHover: { transform: 'translateY(-3px)', boxShadow: '0 14px 26px rgba(0,0,0,0.28)' },
    del: {
      flexShrink: 0,
      width: 27,
      height: 27,
      borderRadius: 11,
      border: 'none',
      background: 'transparent',
      color: c.dim,
      fontSize: 19,
      cursor: 'pointer',
      lineHeight: 1,
      transition: 'color .2s ease',
    },
    shareBtn: {
      flexShrink: 0,
      width: 27,
      height: 27,
      borderRadius: 11,
      border: 'none',
      background: 'transparent',
      color: c.dim,
      fontSize: 15,
      cursor: 'pointer',
      display: 'grid',
      placeItems: 'center',
      transition: 'color .2s ease',
    },
    editBtn: {
      flexShrink: 0,
      fontSize: 10,
      padding: '5px 10px',
      borderRadius: 11,
      border: B,
      background: 'transparent',
      color: c.dim,
      cursor: 'pointer',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
    },
    saveBtn: {
      flexShrink: 0,
      fontSize: 10,
      padding: '6px 12px',
      borderRadius: 11,
      border: '1px solid ' + c.accent,
      background: c.accent,
      color: c.onAccent,
      cursor: 'pointer',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
      fontWeight: 600,
    },
    cancelBtn: {
      flexShrink: 0,
      fontSize: 10,
      padding: '6px 12px',
      borderRadius: 11,
      border: B,
      background: 'transparent',
      color: c.dim,
      cursor: 'pointer',
      letterSpacing: '0.05em',
      textTransform: 'uppercase',
    },
    editInput: {
      flex: 1,
      minWidth: 0,
      padding: '9px 12px',
      borderRadius: 14,
      border: '1px solid ' + c.accent,
      background: c.input,
      color: c.text,
      fontSize: 13,
    },
    editInputSmall: {
      width: 96,
      flexShrink: 0,
      padding: '9px 12px',
      borderRadius: 14,
      border: '1px solid ' + c.accent,
      background: c.input,
      color: c.text,
      fontSize: 13,
    },
    taskMain: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 6 },
    chipRow: { display: 'flex', gap: 6, flexWrap: 'wrap' },
    chip: {
      alignSelf: 'flex-start',
      fontSize: 10,
      padding: '2px 8px',
      borderRadius: 10,
      background: c.input,
      border: B,
      color: c.dim,
      letterSpacing: '0.03em',
    },
    dlTitle: { fontSize: 14, color: c.text, lineHeight: 1.3, cursor: 'pointer' },
    dlDate: { fontSize: 10, color: c.dim, letterSpacing: '0.03em' },
    totalsRow: { display: 'flex', gap: 10 },
    totalCard: {
      flex: 1,
      background: c.card,
      border: B,
      borderRadius: 16,
      padding: '14px 16px',
      display: 'flex',
      flexDirection: 'column',
      gap: 4,
    },
    totalLabel: { fontSize: 10, color: c.dim, letterSpacing: '0.1em', textTransform: 'uppercase' },
    totalVal: { fontSize: 20, fontWeight: 600, color: c.text },
    finNote: { fontSize: 14, color: c.text, lineHeight: 1.3, cursor: 'pointer' },
    finMeta: { fontSize: 10, color: c.dim, letterSpacing: '0.03em' },
    amount: { fontSize: 14, fontWeight: 600, color: c.text, whiteSpace: 'nowrap' },
    ticker,
    tickerDot: { width: 8, height: 8, borderRadius: '50%', flexShrink: 0 },
    tickerLabel: { fontSize: 9, letterSpacing: '0.12em', color: c.dim, flexShrink: 0 },
    tickerTitle: {
      fontSize: 12,
      color: c.text,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    tickerTime: { fontSize: 12, fontWeight: 600, color: c.accent, flexShrink: 0 },
    fab: {
      position: 'fixed',
      bottom: 24,
      right: 24,
      zIndex: 6,
      width: 52,
      height: 52,
      borderRadius: '50%',
      display: 'grid',
      placeItems: 'center',
      background: c.glass,
      backdropFilter: 'blur(24px) saturate(1.5)',
      border: B,
      boxShadow: c.shadow,
      cursor: 'pointer',
      transition: 'transform .25s ease',
      ...bob(3.2, 6.8),
    },
    fabHover: { transform: 'translateY(-3px) scale(1.05)' },
    overlay: {
      position: 'fixed',
      inset: 0,
      zIndex: 6,
      background: 'rgba(5,5,15,0.35)',
      backdropFilter: 'blur(2px)',
    },
    drawerHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
    drawerTitle: {
      fontSize: 15,
      fontWeight: 600,
      letterSpacing: '0.1em',
      textTransform: 'uppercase',
      color: c.text,
    },
    toolbar: {
      display: 'flex',
      flexWrap: 'wrap',
      gap: 6,
      padding: 8,
      borderRadius: 14,
      background: c.card,
      border: B,
    },
    toolBtn: {
      fontSize: 11,
      padding: '6px 9px',
      borderRadius: 10,
      border: B,
      background: 'transparent',
      color: c.text,
      cursor: 'pointer',
      fontWeight: 600,
    },
    editorArea: {
      minHeight: 120,
      maxHeight: 220,
      overflowY: 'auto',
      padding: '12px 14px',
      borderRadius: 14,
      border: '1px solid ' + c.accent,
      background: c.input,
      color: c.text,
      fontSize: 13,
      lineHeight: 1.5,
    },
    noteRendered: { fontSize: 13, lineHeight: 1.5, color: c.text },
    ghShimmer: {
      height: 70,
      borderRadius: 12,
      background: 'linear-gradient(90deg,' + c.input + ' 25%, ' + c.card + ' 50%, ' + c.input + ' 75%)',
      backgroundSize: '200% 100%',
      animation: 'shimmer 1.4s ease-in-out infinite',
    },
    ghGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 },
    ghItem: {
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      background: c.input,
      borderRadius: 10,
      padding: '8px 10px',
    },
    ghLabel: { fontSize: 9, letterSpacing: '0.08em', textTransform: 'uppercase', color: c.dim },
    ghVal: { fontSize: 12, color: c.text },
    dialogOverlay: {
      position: 'fixed',
      inset: 0,
      zIndex: 15,
      background: 'rgba(5,5,15,0.4)',
      backdropFilter: 'blur(4px)',
    },
    dialogHeader: { display: 'flex', alignItems: 'center', gap: 10 },
    dialogTitleInput: {
      flex: 1,
      fontSize: 16,
      fontWeight: 600,
      padding: '8px 12px',
      borderRadius: 14,
      border: B,
      background: c.input,
      color: c.text,
    },
    dialogRow: { display: 'flex', gap: 8, flexWrap: 'wrap' },
    dialogNotes: {
      minHeight: 70,
      padding: '12px 14px',
      borderRadius: 16,
      border: B,
      background: c.input,
      color: c.text,
      fontSize: 13,
      fontFamily: 'inherit',
      resize: 'vertical',
    },
    dialogGithub: {
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      paddingTop: 6,
      borderTop: B,
    },
    dialogActions: { display: 'flex', gap: 8, justifyContent: 'flex-end' },
    notifBanner: {
      position: 'fixed',
      top: isMobile ? 70 : 20,
      left: '50%',
      transform: 'translateX(-50%)',
      zIndex: 17,
      width: 'min(90vw,340px)',
      background: c.glass,
      backdropFilter: 'blur(28px) saturate(1.6)',
      border: '1px solid ' + c.accent,
      borderRadius: 24,
      padding: 16,
      boxShadow: '0 0 30px ' + c.accent + ', ' + c.shadow,
      color: c.text,
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      animation: 'springIn .4s cubic-bezier(.34,1.56,.64,1) both',
    },
    weekdayRow: { display: 'flex', gap: 6 },
    shareCard: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      zIndex: 16,
      width: 'min(92vw,420px)',
      background: c.glass,
      backdropFilter: 'blur(30px) saturate(1.6)',
      border: B,
      borderRadius: 24,
      padding: 22,
      boxShadow: c.shadow,
      color: c.text,
      display: 'flex',
      flexDirection: 'column',
      gap: 14,
      animation: 'springIn .4s cubic-bezier(.34,1.56,.64,1) both',
    },
    toast: {
      position: 'fixed',
      bottom: isMobile ? 90 : 90,
      left: '50%',
      transform: 'translateX(-50%)',
      zIndex: 9,
      display: 'flex',
      alignItems: 'center',
      gap: 10,
      background: c.glass,
      backdropFilter: 'blur(24px) saturate(1.5)',
      border: B,
      borderRadius: 18,
      padding: '10px 14px',
      boxShadow: c.shadow,
      color: c.text,
    },
    toastText: { fontSize: 12, color: c.text },
    brandWrap: {
      position: 'fixed',
      top: 18,
      left: 18,
      zIndex: 12,
      display: 'flex',
      alignItems: 'center',
    },
    menuHead: {
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      padding: '4px 8px 8px',
      borderBottom: B,
      marginBottom: 4,
    },
    menuItem: {
      textAlign: 'left',
      fontSize: 12,
      padding: '9px 8px',
      borderRadius: 12,
      border: 'none',
      background: 'transparent',
      color: c.text,
      cursor: 'pointer',
    },
    avatarMenu: {
      position: 'absolute',
      top: 'calc(100% + 12px)',
      right: 0,
      zIndex: 30,
      width: 222,
      background: c.glass,
      backdropFilter: 'blur(28px) saturate(1.6)',
      '-webkit-backdrop-filter': 'blur(28px) saturate(1.6)',
      border: B,
      borderRadius: 20,
      padding: 10,
      boxShadow: c.shadow + ', inset 0 1px 0 rgba(255,255,255,0.14)',
      display: 'flex',
      flexDirection: 'column',
      gap: 2,
      animation: 'fadeUp .25s ease both',
    },
    ghFab: {
      position: 'fixed',
      bottom: 86,
      right: 24,
      zIndex: 6,
      width: 52,
      height: 52,
      borderRadius: '50%',
      display: 'grid',
      placeItems: 'center',
      background: c.glass,
      backdropFilter: 'blur(24px) saturate(1.5)',
      border: B,
      boxShadow: c.shadow,
      cursor: 'pointer',
      transition: 'transform .25s ease',
      ...bob(3.8, 7),
    },
    ghPanel: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%,-50%)',
      zIndex: 16,
      width: 'min(94vw,520px)',
      maxHeight: '86vh',
      overflowY: 'auto',
      overflowX: 'hidden',
      background: c.glass,
      backdropFilter: 'blur(30px) saturate(1.6)',
      border: B,
      borderRadius: 26,
      padding: 22,
      boxShadow: c.shadow,
      color: c.text,
      display: 'flex',
      flexDirection: 'column',
      gap: 14,
      animation: 'springIn .4s cubic-bezier(.34,1.56,.64,1) both',
    },
    ghLinkCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      alignItems: 'flex-start',
      padding: 16,
      borderRadius: 16,
      background: c.card,
      border: B,
    },
    ghRepoCard: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      padding: '12px 14px',
      borderRadius: 16,
      background: c.card,
      border: B,
    },
    ghRepoMeta: { display: 'flex', gap: 14, fontSize: 10, color: c.dim, flexWrap: 'wrap' },
    ghProgressOuter: { height: 5, borderRadius: 3, background: c.input, overflow: 'hidden' },
    ghSection: {
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
      paddingTop: 8,
      borderTop: B,
      animation: 'fadeUp .3s ease both',
    },
    ghIssueRow: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      padding: '6px 8px',
      borderRadius: 10,
      background: c.input,
    },
    ghIssueText: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      color: c.text,
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    importBtn: {
      flexShrink: 0,
      fontSize: 9,
      padding: '4px 9px',
      borderRadius: 10,
      border: '1px solid ' + c.accent,
      background: 'transparent',
      color: c.accent,
      cursor: 'pointer',
      textTransform: 'uppercase',
      letterSpacing: '0.04em',
    },
    authCard: {
      position: 'fixed',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%,-50%)',
      zIndex: 16,
      width: 'min(92vw,360px)',
      background: c.glass,
      backdropFilter: 'blur(30px) saturate(1.6)',
      border: B,
      borderRadius: 26,
      padding: '30px 26px',
      boxShadow: c.shadow,
      color: c.text,
      display: 'flex',
      flexDirection: 'column',
      gap: 12,
      textAlign: 'center',
      animation: 'springIn .4s cubic-bezier(.34,1.56,.64,1) both',
    },
    authLogo: {
      fontSize: 20,
      letterSpacing: '0.4em',
      fontWeight: 700,
      color: c.text,
      marginBottom: 2,
    },
    authRow: { display: 'flex', gap: 12, width: '100%' },
    authBtn: {
      flex: 1,
      padding: '15px',
      borderRadius: 14,
      border: B,
      background: c.card,
      color: c.text,
      cursor: 'pointer',
      transition: 'transform .2s ease',
      display: 'grid',
      placeItems: 'center',
    },
    authGuest: {
      marginTop: 2,
      padding: '10px',
      borderRadius: 12,
      border: 'none',
      background: 'transparent',
      color: c.dim,
      fontSize: 12,
      cursor: 'pointer',
    },
  }

  return { s, B }
}

// The shared row base used by list items across views.
export function rowBase(c: Theme): Style {
  return {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    borderRadius: 16,
    background: c.card,
    border: '1px solid ' + c.border,
    transition: 'opacity .4s ease, background .4s ease, box-shadow .25s ease',
  }
}
